### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by ibrahimyousri** [Gabesarch/TIDEE#5]
Hello @Gabesarch 

The ai-thor runs and shows multiple views then stops and gives me this error

(TIDEE) ibrahim@ibrahim:~/TIDEE2/TIDEE$ python main.py --mode rearrangement --tag TIDEE_rearrengement_2023 --OT_dist_thresh 1.0 --thresh_num_dissimilar -1 --match_relations_walk --HORIZON_DT 30 --log_every 25 --dataset 2023 --eval_split combined --server_port 1
DATASET IS 2023
Note: mapping sliced classes to non-sliced in SOLQ
set name= test00
Sampling 2800 tasks from the Two-Phase combined dataset (2800 unique tasks)
WARNING:py.warnings:/home/ibrahim/TIDEE2/TIDEE/SOLQ/models/ops/modules/ms_deform_attn.py:47: UserWarning: You'd better set d_model in MSDeformAttn to make the dimension of each attention head a power of 2 which is more efficient in our CUDA implementation.
  warnings.warn("You'd better set d_model in MSDeformAttn to make the dimension of each attention head a power of 2 "

Training with relu.
Training with vector_hidden_dim 1024.
Training with 6 vector stages.
Training with vector_loss_coef 3.
Training with vector_loss_norm.
...found checkpoint ./checkpoints/solq-00018500.pth
90 30 0.25

Starting task 0
PHASE: combined Estimated depth? False Noisy depth? False Noisy pose? False
SUBMISSION NAME: ./metrics/submission_combined_original_estimateDepth=False_noisyDepth=False_noisyPose=False_TIDEE_rearrengement_2023.json.gz
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    main()
  File "main.py", line 23, in main
    aithor_rearrangement.main()
  File "/home/ibrahim/TIDEE2/TIDEE/models/aithor_rearrange.py", line 258, in main
    walkthrough_task = self.two_phase_rgb_task_sampler.next_task()
  File "/home/ibrahim/TIDEE2/TIDEE/rearrangement/rearrange/tasks.py", line 1142, in next_task
    raise e
  File "/home/ibrahim/TIDEE2/TIDEE/rearrangement/rearrange/tasks.py", line 1065, in next_task
    self.unshuffle_env.reset(
  File "/home/ibrahim/TIDEE2/TIDEE/rearrangement/rearrange/environment.py", line 1451, in reset
    self._task_spec_reset(
  File "/home/ibrahim/TIDEE2/TIDEE/rearrangement/rearrange/environment.py", line 1410, in _task_spec_reset
    current_obj_info = next(
StopIteration

**Comment by Gabesarch** [comment]
Hi Ibrahim,

I have just pushed a new import for the rearrangement package that may help fix your issue. Can you try pulling the newest commit and re-running `setup.sh`? 

Best, 
Gabe

**Comment by ibrahimyousri** [comment]
Thank you Gabe for your consideration and help!

Unfortunately, after even re-installing TIDEE the problem still exists.
However, when running it on the 2022 dataset it ran without any problems even before the new commit you added.
 

python main.py --mode rearrangement --tag TIDEE_rearrengement_2023 --OT_dist_thresh 1.0 --thresh_num_dissimilar -1 --match_relations_walk --HORIZON_DT 30 --log_every 25 --dataset 2022 --eval_split combined --server_port 1

![Screenshot from 2023-11-24 22-57-56](https://github.com/Gabesarch/TIDEE/assets/43193294/497ad5be-b15b-4b9c-83f6-2700f695c85f)

**Comment by Gabesarch** [comment]
Hi, Are you running on the `rearrange2023` branch and installing the requirements.txt and setup from that branch?

**Comment by ibrahimyousri** [comment]
yes from [here](https://github.com/Gabesarch/TIDEE/tree/rearrange2023) specifically
